#!/bin/bash

set -e -u

# Set locales and keyboard
mv /etc/locale.gen /etc/locale.gen.orig
echo "en_GB.UTF-8 UTF-8" > /etc/locale.gen
locale-gen
# localectl set-locale LANG=en_GB.UTF-8
# localectl set-x11-keymap gb "" mac
ln -sf /usr/share/zoneinfo/GB /etc/localtime

# Enable lightdm and graphical login
systemctl -fq enable lightdm
systemctl disable multi-user.target
systemctl set-default graphical.target
echo "auth  sufficient  pam_succeed_if.so user  ingroup nopasswdlogin" >> /etc/pam.d/lightdm

# Allow root to autologin
groupadd -r autologin
groupadd -r nopasswdlogin
usermod -a -G autologin,nopasswdlogin root
chmod 750 /etc/sudoers.d
chmod 440 /etc/sudoers.d/g_wheel

# Create a non-root user
useradd -m -G autologin,nopasswdlogin,wheel -s /bin/bash liveuser
passwd -d liveuser

# Enable VirtualBox guest services
systemctl -fq enable vboxservice

# Enable system services
systemctl -fq enable NetworkManager ntpd
gsettings set org.gnome.desktop.datetime automatic-timezone true
