#!/bin/bash

set -e -u

# Set locales and keyboard
mv /etc/locale.gen /etc/locale.gen.orig
echo "en_GB.UTF-8 UTF-8" > /etc/locale.gen
locale-gen
localectl set-locale LANG=en_GB.UTF-8
localectl set-x11-keymap gb "" mac

# Enable lightdm and graphical login
systemctl enable lightdm.service
systemctl disable multi-user.target
systemctl set-default graphical.target
echo "auth  sufficient  pam_succeed_if.so user  ingroup nopasswdlogin" >> /etc/pam.d/lightdm

# Allow root to autologin
groupadd -r autologin
groupadd -r nopasswdlogin
usermod -a -G autologin,nopasswdlogin root

# Create a non-root user
useradd -m -G autologin,nopasswdlogin,wheel -s /bin/bash live
echo live:live | chpasswd

# Enable VirtualBox guest services
systemctl enable vboxservice.service

# Enable ntp
timedatectl set-ntp true
gsettings set org.gnome.desktop.datetime automatic-timezone true
