#!/bin/bash

set -e -u

# Enable the ntpd time service
systemctl enable ntpd.service

# Enable lightdm and graphical login
systemctl enable lightdm.service
systemctl disable multi-user.target
systemctl set-default graphical.target
echo "auth  sufficient  pam_succeed_if.so user  ingroup nopasswdlogin" >> /etc/pam.d/lightdm

# Allow root to autologin
groupadd -r autologin
groupadd -r nopasswdlogin
usermod -a -G autologin,nopasswdlogin root

# Enable VirtualBox guest services
systemctl enable vboxservice.service
