#!/bin/bash
set -eu

cp -avn /usr/share/live/build/bootloaders/isolinux/* config/bootloaders/isolinux

lb config noauto \
  --apt-indices false \
  --apt-source-archives false \
  --archive-areas "main contrib non-free" \
  --backports true \
  --binary-images iso-hybrid \
  --debian-installer false \
  --memtest none \
  --source false \
  --system live \
  --win32-loader false \
  --zsync false \
  "$@" 2>&1 | tee /tmp/logs/build.log
