#!/bin/bash
set -eu

lb config noauto \
  --architecture amd64 \
  --apt-indices false \
  --apt-recommends false \
  --apt-source-archives false \
  --binary-images iso-hybrid \
  --debian-installer false \
  --distribution "xenial" \
	--linux-flavours amd64 \
  --memtest none \
  --mode ubuntu \
  --source false \
  --system live \
  --win32-loader false \
  --zsync false \
  "$@" 2>&1 | tee /tmp/logs/build.log
